# Generated by Django 4.1.2 on 2022-10-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cc',
            field=models.CharField(default='', max_length=19),
        ),
    ]
