# Generated by Django 4.1.2 on 2022-10-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2', '0002_user_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cc',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
    ]
